trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    languages: 'csharp, javascript'
    querysuite: 'security-extended'
- task: AdvancedSecurity-Codeql-Autobuild@1


- task: AdvancedSecurity-Codeql-Analyze@1
- task: AdvancedSecurity-Publish@1